/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function compress(input: Buffer, level?: number | undefined | null): Promise<Buffer>
export function decompress(input: Buffer): Promise<Buffer>
