/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function decompress(compressionType: 'bzip2' | 'zstd', input: Buffer): Promise<Buffer>
export function compress(compressionType: 'bzip2' | 'zstd', input: Buffer, level: number): Promise<Buffer>
