# TODO: reuse common steps using YAML anchors
# partial YAML anchors support got added in early Aug 2025, see https://github.com/actions/runner/issues/1182
# but defining a block of steps under a single anchor is still not supported

name: GitHub Actions CI
'on':
  push:
    branches:
      - wip
  pull_request:
    branches:
      - master
env:
  ELECTRON_MAIL_NODE_VERSION: 24
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
permissions:
  contents: read
jobs:
  package-app:
    if: github.event_name == 'push'
    strategy:
      matrix:
        os:
          - windows-11-arm
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - &common-step_checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # (v6) 2026-06-02
        with:
          persist-credentials: false
      - &common-step_setup-pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # (v6.1.0) 2026-09-05
        with:
          version: latest
      - &common-step_setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # (v6) 2026-04-20
        with:
          node-version: ${{ env.ELECTRON_MAIL_NODE_VERSION }}
          cache: pnpm
      - &common-step_envinfo
        name: envinfo
        run: npx envinfo
      - &common-step_install-node-modules
        name: install node modules
        run: pnpm install --frozen-lockfile --reporter=append-only
      - name: build
        if: runner.os == 'Windows'
        run: ./scripts/ci/github/package-app.ps1
